-- AlterTable
ALTER TABLE "OwnerConfig" ADD COLUMN     "aiMaxTokens" INTEGER NOT NULL DEFAULT 1024,
ADD COLUMN     "aiSystemPrompt" TEXT,
ADD COLUMN     "aiTemperature" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
ADD COLUMN     "aiTone" TEXT NOT NULL DEFAULT 'HELPFUL',
ADD COLUMN     "aiTopK" INTEGER NOT NULL DEFAULT 40,
ADD COLUMN     "aiTopP" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
